# Generated by Django 4.1.7 on 2023-03-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
